### ISSUE TITLE
Add examples of continue and break in control flow presentation (links to solution 5)

### ISSUE THREAD

**Issue by tommygod3** [tommygod3/ncas-isc#26]
Need one or two slides to explain `continue` and `break`. Note that solution 5 needs to know about this stuff.

**Comment by tommygod3** [comment]
https://github.com/ncasuk/ncas-isc/issues/24

**Comment by tommygod3** [comment]
break, continue and pass explanations added to flow presentations, I decided not to change code snippet mentioned in https://github.com/ncasuk/ncas-isc/issues/24 because both work okay and I think the original way is just as good to demonstrate file reading; "while True" may also be a bad tool to teach beginners.

**Comment by alaniwi** [comment]
I really don't like the substantive line (in this case `line = reader.readline()`) being repeated in more than one place.

To avoid `while True`, I suppose you could have something like
```
finished = False
while not finished:
    line = reader.readline()
    if line:
        print(line)
    else:
        finished = True
```

**Comment by tommygod3** [comment]
I think the best way to do it is with a for loop, but this example is just demonstrating that it can be done with a while loop also. And I agree that repeating code isn't a good habit so perhaps this is a better solution.

**Comment by alaniwi** [comment]
Oh undoubtedly the best in this special case is a `for` loop (`for line in reader:`), but if we are going to show how in general to do this kind of `while` loop, I would be happier with some kind of solution that avoids repeating substantive line of code (even if at the expense of longer overall code because of the control flow baggage needed to implement it). I don't think that `while True` is a problem TBH, but just pointing out that it can be avoided.

**Comment by alaniwi** [comment]
I still prefer the `while True` solution (although maybe with `if line == ''` rather than the `if not line` in my original suggestion).

**Comment by tommygod3** [comment]
I have gone with @alaniwi's suggestion of the ```while True``` solution as it is more elegant and less confusing

**Comment by alaniwi** [comment]
Thanks
